export const annotations = [
  {
    id: "1",
    createdAt: "12 de agosto de 2024",
    remindAt: "15 de agosto de 2024 - 11:25",
    text: "Lembrete para reunião com o time de desenvolvimento.",
    image: null,
    category: "Trabalho",
    status: "Pendente",
    creator: "Cristiano Silva",
    collaborators: ["Cristiano Silva", "Camila Moretti"],
  },
  {
    id: "2",
    createdAt: "13 de agosto de 2024",
    remindAt: "16 de agosto de 2024 - 11:25",
    text: "Enviar relatório de progresso do projeto.",
    image: "/fototeste.png",
    category: "Trabalho",
    status: "Pendente",
    creator: "Cristiano Silva",
    collaborators: ["Cristiano Silva", "Joaquim Santos"],
  },
  {
    id: "3",
    createdAt: "14 de agosto de 2024",
    remindAt: "17 de agosto de 2024 - 11:25",
    text: "Lembrete para check-up médico anual.",
    image: null,
    category: "Saúde",
    status: "Pendente",
    creator: "Cristiano Silva",
    collaborators: ["Cristiano Silva"],
  },
  {
    id: "4",
    createdAt: "10 de agosto de 2024",
    remindAt: "18 de agosto de 2024 - 11:25",
    text: "Reunião com o cliente para apresentação final.",
    image: null,
    category: "Trabalho",
    status: "Pendente",
    creator: "Cristiano Silva",
    collaborators: ["Cristiano Silva", "Camila Moretti"],
  },
  {
    id: "5",
    createdAt: "15 de agosto de 2024",
    remindAt: "19 de agosto de 2024 - 11:25",
    text: "Comprar ingressos para o show do fim de semana.",
    image: null,
    category: "Lazer",
    status: "Pendente",
    creator: "Cristiano Silva",
    collaborators: ["Cristiano Silva", "Maria Silva"],
  },
  {
    id: "6",
    createdAt: "11 de agosto de 2024",
    remindAt: "20 de agosto de 2024 - 11:25",
    text: "Lembrete para renovar a assinatura do software.",
    image: "/fototeste.png",
    category: "Trabalho",
    status: "Pendente",
    creator: "Cristiano Silva",
    collaborators: ["Cristiano Silva"],
  },
];
